retest

diff --git a/.github/workflows/validate_doxygen.yml b/.github/workflows/validate_doxygen.yml
--- a/.github/workflows/validate_doxygen.yml
+++ b/.github/workflows/validate_doxygen.yml
@@ -6,72 +6,130 @@ on:
 
 jobs:
 
-  CodeCoverage:
-    runs-on: ubuntu-latest
+  CMakeBuild:
+    runs-on: windows-latest
 
     env:
-      COVERAGE_DATA_PATH: extras/coverage-data/coverage.info
+      CMAKE_TOOLCHAIN_FILE: C:\vcpkg\scripts\buildsystems\vcpkg.cmake
+      VCPKG_ROOT: C:\vcpkg
+      # Path containing the CMakeLists.txt for the tests.
+      SOURCE_PATH: ${{ github.workspace }}
+      # Path of the top-level folder for build output.
+      BUILD_PATH: ${{ github.workspace }}\build
 
     steps:
-      - uses: actions/checkout@v2
-
-      - uses: arduino/cpp-test-action@v1
-        with:
-          coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}
-
-      # Optional: upload coverage report to codecov.io
-      # - uses: codecov/codecov-action@v1
-      #   with:
-      #     file: ${{ env.COVERAGE_DATA_PATH }}
-
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-        token: ${{ secrets.GITHUB_TOKEN }}
+    - uses: actions/checkout@v2
 
     - name: Install Dependencies
       run: |
-        sudo apt-get update && sudo apt-get install -y \
-          doxygen \
-          graphviz
+        vcpkg install
+        choco install ninja lcov
 
-    - name: Remove old comments
-      uses: izhangzhihao/delete-comment@master
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        delete_user_name: EreliaStudio
-        issue_number: ${{ github.event.number }}
+    - name: Configure the project with CMake
+      run: cmake --preset test
 
-    - name: Generate Doxygen
-      run: doxygen Doxyfile
+    - name: Configure the project with CMake
+      run: cmake --build --preset test
 
-    - name: Refine warnings and check if they exist
-      id: check_warnings
+    - name: Build tests
       run: |
-        if [ -s doxygen_warnings.log ]; then
-          sed -i 's/\/home\/runner\/work\/Sparkle\/Sparkle\//- /g' doxygen_warnings.log
-          sed -i 's/: warning:/\n/g' doxygen_warnings.log
-          awk '{if (!/^-/) print "    "$0; else print $0;}' doxygen_warnings.log > tmp && mv tmp doxygen_warnings.log
-          awk '{if (NR!=1 && /^-/) print "\n\n"; print $0;}' doxygen_warnings.log > tmp && mv tmp doxygen_warnings.log
-          echo -e "There is a list of documentation error you need to fix before merging this PullRequest :\n\n" | cat - doxygen_warnings.log > tmp && mv tmp doxygen_warnings.log
-          echo "check_warnings=true" >> $GITHUB_ENV
-        else
-          echo "check_warnings=false" >> $GITHUB_ENV
-        fi
-    
-    - name: Create comment if warnings exist
-      if: env.check_warnings == 'true'
-      uses: peter-evans/create-or-update-comment@v3
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
-        issue-number: ${{ github.event.pull_request.number }}
-        body-path: 'doxygen_warnings.log'
+        cd ${{ env.BUILD_PATH }}
+        ctest
 
-    - name: Fail the workflow if warnings exist
-      if: env.check_warnings == 'true'
-      run: exit 1
+    - name: Upload build artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: cmake_build
+        path: ${{ env.BUILD_PATH }}
+
+
+  CodeCoverage:
+    needs: CMakeBuild
+    runs-on: ubuntu-latest
+
+    env:
+      # Path of the top-level folder for build output.
+      BUILD_PATH: ${{ github.workspace }}/build/test
+      # Path to save the coverage data file to.
+      COVERAGE_DATA_PATH: ${{ github.workspace }}/coverage.info
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Download build artifact
+      uses: actions/download-artifact@v4
+      with:
+        name: cmake_build
+        path: build
+
+    - name: Build tests
+      run: ls -lhaR build/
+
+  #   - name: Install LCOV
+  #     shell: bash
+  #     run: sudo apt install -y lcov valgrind > /dev/null
+
+  #   # - name: Run valgrind
+  #   #   shell: bash
+  #   #   run: valgrind --tool=memcheck --leak-check=yes --error-exitcode=1
+    
+  #   - name: Generate code coverage
+  #     shell: bash
+  #     run: lcov --directory "${{ env.BUILD_PATH }}" --capture --output-file "${{ env.COVERAGE_DATA_PATH }}"
+
+  #   - name: Display coverage report in log
+  #     shell: bash
+  #     run: lcov --list "${{ env.COVERAGE_DATA_PATH }}"
+
+  # build:
+  #   runs-on: ubuntu-latest
+
+  #   steps:
+  #   - name: Checkout repository
+  #     uses: actions/checkout@v2
+  #     with:
+  #       fetch-depth: 0
+  #       token: ${{ secrets.GITHUB_TOKEN }}
+
+  #   - name: Install Dependencies
+  #     run: |
+  #       sudo apt-get update && sudo apt-get install -y \
+  #         doxygen \
+  #         graphviz \
+  #         libglew-dev
+
+  #   - name: Remove old comments
+  #     uses: izhangzhihao/delete-comment@master
+  #     with:
+  #       github_token: ${{ secrets.GITHUB_TOKEN }}
+  #       delete_user_name: EreliaStudio
+  #       issue_number: ${{ github.event.number }}
+
+  #   - name: Generate Doxygen
+  #     run: doxygen Doxyfile
+
+  #   - name: Refine warnings and check if they exist
+  #     id: check_warnings
+  #     run: |
+  #       if [ -s doxygen_warnings.log ]; then
+  #         sed -i 's/\/home\/runner\/work\/Sparkle\/Sparkle\//- /g' doxygen_warnings.log
+  #         sed -i 's/: warning:/\n/g' doxygen_warnings.log
+  #         awk '{if (!/^-/) print "    "$0; else print $0;}' doxygen_warnings.log > tmp && mv tmp doxygen_warnings.log
+  #         awk '{if (NR!=1 && /^-/) print "\n\n"; print $0;}' doxygen_warnings.log > tmp && mv tmp doxygen_warnings.log
+  #         echo -e "There is a list of documentation error you need to fix before merging this PullRequest :\n\n" | cat - doxygen_warnings.log > tmp && mv tmp doxygen_warnings.log
+  #         echo "check_warnings=true" >> $GITHUB_ENV
+  #       else
+  #         echo "check_warnings=false" >> $GITHUB_ENV
+  #       fi
+    
+    # - name: Create comment if warnings exist
+    #   if: env.check_warnings == 'true'
+    #   uses: peter-evans/create-or-update-comment@v3
+    #   with:
+    #     token: ${{ secrets.GITHUB_TOKEN }}
+    #     issue-number: ${{ github.event.pull_request.number }}
+    #     body-path: 'doxygen_warnings.log'
+
+    # - name: Fail the workflow if warnings exist
+    #   if: env.check_warnings == 'true'
+    #   run: exit 1
